### ISSUE TITLE
As a user I want to have nedry send an email to the individual's computer.

### ISSUE THREAD

**Issue by gsaarinen** [gdcodeclub/nedry#11]

**Comment by lpillman** [comment]
Jim and I are interested in taking a look at this one.

**Comment by eebbesen** [comment]
http://guides.rubyonrails.org/action_mailer_basics.html

**Comment by lpillman** [comment]
@eebbesen couldn't we use the TMS client instead? http://www.rubydoc.info/gems/govdelivery-tms/0.8.9. Is the mailer another way to do this?

**Comment by lpillman** [comment]
Jim: We needed to write the test first. 

To your questions tho: 
1. Yes, we do need to require the gem at the top.
2. Do we need to create a separate file? Or can we include it the offense controller? We can include it right in the offense controller since our code is going to pretty small.

**Comment by kmarekspartz** [comment]
@edlebert has talked about making a TMS Client strategy for ActionMailer, so if you use ActionMailer now, you may be able to switch to TMS Client later with a small amount of configuration.

**Comment by lpillman** [comment]
That is interesting @zeckalpha. Jim and I want to have an excuse to use the TMS mailer gem so I think we will be using that directly. It is too bad more clients don't use ruby for a programming language. Your documentation seems pretty extensive.

**Comment by lpillman** [comment]
- [x] created new branch
- [x] added a new test
- [x] added code so we are able to send an email. 

Still to do: 
- [ ] figure out how to hide the TMS token
- [ ] change the email address to the variable. 
- [ ] build an email template with nedry as a GIF in the email.

**Comment by richardgfong** [comment]
Thing to think about (out of scope right now):
- [ ] capture messageID from XACT
- [ ] drop messageID into Table
- [ ] get  email status

**Comment by lpillman** [comment]
I have added the Heroku Config Var of TMS_TOKEN with the actual token.

**Comment by richardgfong** [comment]
Try adding tms_token to my BASH profile

**Comment by beja0502** [comment]
Added Email/SMS and tests
